apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaultbackend-k8s-lib-unb-ca
  labels:
    app: defaultbackend-k8s-lib-unb-ca
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defaultbackend-k8s-lib-unb-ca
  template:
    metadata:
      labels:
        app: defaultbackend-k8s-lib-unb-ca
    spec:
      nodeSelector:
        deploy_prod: 'true'
      terminationGracePeriodSeconds: 60
      containers:
        - name: defaultbackend-k8s-lib-unb-ca
          image: "||DEPLOYMENTIMAGE||"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
